
require "pathname"
require 'set'

APP_NAME = 'Samizdat'

SRC_FOLDERS= [
	'Samizdat',
	'samlib',
]

LOCALIZED_XIBS = [
	'AddAuthorView',
	'AuthorInfoView',
	'CommentsView',
	'MainMenu',
]

def system_or_exit(cmd, stdout = nil)
  puts "Executing #{cmd}"
  cmd += " >#{stdout}" if stdout
  system(cmd) or raise "******** Build failed ********"
end

def makeLocalizable

 	outpath = Pathname.pwd + "Samizdat/en.lproj/Localizable.strings"

	r = /\"(.+)\"/	
	strings = Set.new
	if outpath.file?
		outpath.each_line do |line|
			strings += line.split("=")[0].scan(r)
		end	
	end

	#r = /locString\(@"([\w|\s]+)"\)/
	r = /locString\(@"(.+)"\)/
	newStrings = Set.new

	SRC_FOLDERS.each do |folder|
		srcpath = Pathname.pwd + folder
		if srcpath.directory?
			srcpath.children(false).each do |file|
				next unless ".m" == file.extname
				filepath = srcpath + file
		 		filepath.each_line do |line|  		 		
		 			line.scan(r).each do |s|
		 				newStrings += s unless strings.include?(s)
		 			end	
		 		end 
		  	end
		end  	
	 end 	
			
	unless newStrings.empty?		
		File.open(outpath, 'a') do |file| 
			file.puts "//generated by rake at #{Time.new}"
			newStrings.each do |s|
				file.puts "\"#{s}\" = \"#{s}\";" 
			end					
		end
	end	

	newStrings.length
end


desc 'Generate Localizable.strings'
task :localizable do |t|
  print ' * generate Localizable.strings' 
  n = makeLocalizable
  print ": append #{n} strings\n"
end

desc 'Generate .strings file from .xib'
task :stringsFromXib do |t|	
	LOCALIZED_XIBS.each do |xibName|
		ruStrings = "Samizdat/ru.lproj/#{xibName}.strings"
		xibFile = "Samizdat/en.lproj/#{xibName}.xib"
		Pathname.new(xibFile).file? or raise "******** No #{xibFile} ********"		
		system_or_exit "ibtool --generate-strings-file #{ruStrings} #{xibFile}"	
	end	
end	

desc 'Generate localized .xib from .strings'
task :localizeXib do |t|	
	LOCALIZED_XIBS.each do |xibName|
		ruStrings = "Samizdat/ru.lproj/#{xibName}.strings"
		enXib = "Samizdat/en.lproj/#{xibName}.xib"
		ruXib = "Samizdat/ru.lproj/#{xibName}.xib"
		Pathname.new(ruStrings).file? or raise "******** No #{ruStrings} ********"
		Pathname.new(enXib).file? or raise "******** No #{enXib} ********"
		system_or_exit "ibtool --strings-file #{ruStrings} #{enXib} --write #{ruXib}"	
	end	
end	

# 
desc 'create .dmg with app'
task :dmg do |t|
	folder = Pathname.new 'tmp'
	srcPath = folder + 'osx'
	dmgPath = folder + "#{APP_NAME}.dmg"
	ro_dmgPath = folder + "#{APP_NAME}_ro.dmg"
	dmgPath.delete if dmgPath.exist?
	system_or_exit "hdiutil create -ov -srcfolder #{srcPath} -format UDRW -volname \"#{APP_NAME} Image\" #{dmgPath}"	
	system_or_exit "hdiutil convert #{dmgPath} -format UDZO -imagekey zlib-level=9 -o #{ro_dmgPath}"
	dmgPath.delete
	ro_dmgPath.rename dmgPath
end	

PROJECT_NAME = 'samlib'
TARGET_NAME = 'Samizdat'
SCHEME_NAME = 'Samizdat'
CONFIGURATION = 'Release'

desc "Clean"
task :clean do
	buildDir = Pathname.new 'tmp/build'	
  	system_or_exit "xcodebuild -project #{PROJECT_NAME}.xcodeproj -target #{TARGET_NAME} -configuration #{CONFIGURATION} clean SYMROOT=#{buildDir}"
end

desc "Build"
task :build do
	buildDir = Pathname.new 'tmp/build'		
	system_or_exit "xcodebuild -project #{PROJECT_NAME}.xcodeproj -target #{TARGET_NAME} -sdk macosx10.7 -configuration #{CONFIGURATION} build TEST_AFTER_BUILD=NO SYMROOT=#{buildDir}"
	#system_or_exit "xcodebuild -project #{PROJECT_NAME}.xcodeproj -target #{TARGET_NAME} -sdk macosx10.7 -configuration #{CONFIGURATION} build"
end

desc "Archive"
task :archive do
	# xcodebuild -project projectname -activetarget -activeconfiguration archive
	system_or_exit "xcodebuild -scheme #{SCHEME_NAME} archive"
end	
